name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev python3-dev ffmpeg apktool openjdk-17-jdk

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Clean Old Cache
      run: |
        # هذا الأمر السحري سيمسح أي خطأ قديم معلق في السيرفر رغماً عنه
        buildozer android clean

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
      env:
        ACCEPT_SDK_LICENSE: "y"

    - name: Upload finished APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Premium-Locker-APK
        path: bin/*.apk
    
